const studentsDatabase = {
  'jensmaykol@gmail.com': {
    name: 'Armas Pinedo Jens Maykol',
    password: 'jensmaykol',
    nota1: 17,
    nota2: 17,
    nota3: 0,
    nota4: 13,
    nota5: 0,
    final: 9,
  },
  'jesuscafdenas@gmail.com': {
    name: 'Cardenas Pinchi Wagner Jesús',
    password: 'jesuscafdenas',
    nota1: 16,
    nota2: 18,
    nota3: 15,
    nota4: 10,
    nota5: 13,
    final: 14,
  },
  'claudiagaraypua@gmail.com': {
    name: 'Garay Pua Claudia Natividad',
    password: 'claudiagaraypua',
    nota1: 19,
    nota2: 16,
    nota3: 19,
    nota4: 19,
    nota5: 16,
    final: 18,
  },
  'rodrigozafeth04@gmail.com': {
    name: 'Garcia Cordova Rodrigo Zafeth',
    password: 'rodrigozafeth04',
    nota1: 14,
    nota2: 16,
    nota3: 15,
    nota4: 0,
    nota5: 0,
    final: 9,
  },
  'garciayenifer590@gmail.com': {
    name: 'Garcia Labajos Yenifer Aracely',
    password: 'garciayenifer590',
    nota1: 0,
    nota2: 10,
    nota3: 16,
    nota4: 17,
    nota5: 0,
    final: 9,
  },
  'kisuiza67@gmail.com': {
    name: 'Ishuiza Garcia Karen Jimena',
    password: 'kisuiza67',
    nota1: 18,
    nota2: 18,
    nota3: 19,
    nota4: 0,
    nota5: 13,
    final: 14,
  },
  'frankcristianjimenezsatalaya@gmail.com': {
    name: 'Jiménez satalaya Frank Cristian',
    password: 'frankcristianjimenezsatalaya',
    nota1: 0,
    nota2: 0,
    nota3: 0,
    nota4: 0,
    nota5: 4,
    final: 1,
  },
  'beatrizjimene1@gmail.com': {
    name: 'Jimenez Torres Stephanie Beatriz',
    password: 'beatrizjimene1',
    nota1: 17,
    nota2: 20,
    nota3: 19,
    nota4: 18,
    nota5: 18,
    final: 18,
  },
  'sinticarlos994@gmail.com': {
    name: 'Macahuchi sinti Carlos manuel',
    password: 'sinticarlos994',
    nota1: 0,
    nota2: 15,
    nota3: 15,
    nota4: 0,
    nota5: 0,
    final: 6,
  },
  'montalvanauria20@gmail.com': {
    name: 'Montalvan Aguirre Aurialuz',
    password: 'montalvanauria20',
    nota1: 19,
    nota2: 18,
    nota3: 19,
    nota4: 18,
    nota5: 20,
    final: 19,
  },
  'maxbellojanamaflores@gmail.com': {
    name: 'Ojanama Flores Maxbell',
    password: 'maxbellojanamaflores',
    nota1: 18,
    nota2: 16,
    nota3: 18,
    nota4: 18,
    nota5: 0,
    final: 14,
  },
  'antonioojedasalas@gmail.com': {
    name: 'Ojeda salas Antonio',
    password: 'antonioojedasalas',
    nota1: 13,
    nota2: 16,
    nota3: 0,
    nota4: 0,
    nota5: 0,
    final: 6,
  },
  'greissiluz90@gmail.com': {
    name: 'Paima García Greissi Luz',
    password: 'greissiluz90',
    nota1: 20,
    nota2: 16,
    nota3: 16,
    nota4: 17,
    nota5: 0,
    final: 14,
  },
  'silvanaperezsaavedra@gmail.com': {
    name: 'Perez Saavedra Bertha Silvana',
    password: 'silvanaperezsaavedra',
    nota1: 18,
    nota2: 0,
    nota3: 17,
    nota4: 18,
    nota5: 16,
    final: 14,
  },
  'masselyp@gmail.com': {
    name: 'Pinedo Maytahuari Massely',
    password: 'masselyp',
    nota1: 13,
    nota2: 12,
    nota3: 0,
    nota4: 0,
    nota5: 0,
    final: 5,
  },
  'rengifojack014@gmail.com': {
    name: 'Rengifo Chashnamote Jack',
    password: 'rengifojack014',
    nota1: 0,
    nota2: 0,
    nota3: 0,
    nota4: 0,
    nota5: 0,
    final: 0,
  },
  'joneirengifo1606@gmail.com': {
    name: 'Rengifo Rengifo Carlos Jonei',
    password: 'joneirengifo1606',
    nota1: 0,
    nota2: 0,
    nota3: 15,
    nota4: 12,
    nota5: 0,
    final: 5,
  },
  'krioscenepo@gmail.com': {
    name: 'Rios Cenepo Karen',
    password: 'krioscenepo',
    nota1: 18,
    nota2: 0,
    nota3: 17,
    nota4: 13,
    nota5: 4,
    final: 10,
  },
  'angelapatriciarojascordova28@gmail.com': {
    name: 'Rojas Cordova Angela Patricia',
    password: 'angelapatriciarojascordova28',
    nota1: 19,
    nota2: 16,
    nota3: 14,
    nota4: 14,
    nota5: 5,
    final: 14,
  },
  'sruizvasquez@gmail.com': {
    name: 'Ruiz Vasquez Santiago Andres',
    password: 'sruizvasquez',
    nota1: 10,
    nota2: 10,
    nota3: 10,
    nota4: 10,
    nota5: 10,
    final: 10,
  },
  'evelinsaboya147@gmail.com': {
    name: 'Saboya Chujutalli Evelin',
    password: 'evelinsaboya147',
    nota1: 0,
    nota2: 15,
    nota3: 0,
    nota4: 0,
    nota5: 0,
    final: 3,
  },
  'ciroalavradosandoval@gmail.com': {
    name: 'Sandoval Ciro Alvarado',
    password: 'ciroalavradosandoval',
    nota1: 18,
    nota2: 16,
    nota3: 0,
    nota4: 0,
    nota5: 0,
    final: 7,
  },
  'limbersangama.2025@gmail.com': {
    name: 'Sangama cachique Limber',
    password: 'limbersangama.2025',
    nota1: 0,
    nota2: 5,
    nota3: 15,
    nota4: 14,
    nota5: 4,
    final: 8,
  },
  'sangamasalash@gmail.com': {
    name: 'Sangama salas Hans christian',
    password: 'sangamasalash',
    nota1: 0,
    nota2: 0,
    nota3: 0,
    nota4: 0,
    nota5: 2,
    final: 0.4,
  },
  'jose.satalaya2002@gmail.com': {
    name: 'Satalaya Segura José Luis',
    password: 'jose.satalaya2002',
    nota1: 20,
    nota2: 19,
    nota3: 18,
    nota4: 18,
    nota5: 20,
    final: 19,
  },
  'shariandavasqueze@gmail.com': {
    name: 'Sharianda Vasquez Elvis',
    password: 'shariandavasqueze',
    nota1: 0,
    nota2: 0,
    nota3: 0,
    nota4: 0,
    nota5: 0,
    final: 0,
  },
  'bsoriat14@gmail.com': {
    name: 'Soria Trauco Benjamín',
    password: 'bsoriat14',
    nota1: 10,
    nota2: 18,
    nota3: 15,
    nota4: 16,
    nota5: 0,
    final: 12,
  },
  'migueltellotorres07@gmail.com': {
    name: 'Tello Torres. David Miguel',
    password: 'migueltellotorres07',
    nota1: 0,
    nota2: 0,
    nota3: 0,
    nota4: 0,
    nota5: 2,
    final: 0.4,
  },
  'tuanamsangamaluisisaias00@gmail.com': {
    name: 'Tuanama sangama Luis isaias',
    password: 'tuanamsangamaluisisaias00',
    nota1: 0,
    nota2: 0,
    nota3: 0,
    nota4: 0,
    nota5: 0,
    final: 0,
  },
  'lindavela086@gmail.com': {
    name: 'Vela sangama Linda',
    password: 'lindavela086',
    nota1: 0,
    nota2: 5,
    nota3: 18,
    nota4: 15,
    nota5: 8,
    final: 9,
  },
  'karenvivianazapatapinedo@gmail.com': {
    name: 'Zapata Pinedo Karen Viviana',
    password: 'karenvivianazapatapinedo',
    nota1: 16,
    nota2: 18,
    nota3: 14,
    nota4: 13,
    nota5: 2,
    final: 13,
  },
};
